CREATE USER BikeShopWebsite WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT PASSWORD 'password';

GRANT CONNECT ON DATABASE "BikeShop" TO BikeShopWebsite; 

CREATE TABLE BikeInfo 
(	
Id SERIAL CONSTRAINT PK_BikeInfo_Id PRIMARY KEY,
Description VARCHAR(500) NOT NULL,
Price MONEY NOT NULL,
Rating FLOAT NOT NULL,
Quantity INT NOT NULL,
Type VARCHAR(50) NOT NULL
);


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO BikeShopWebsite;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO BikeShopWebsite;